version: 0.1
phases:
 install:
  commands:
   - aws cloudformation package --template-file serverless.template --s3-bucket samtestapi-coderepo1 --output-template-file outputSamTemplate.yaml
artifacts:
 type: zip
 files:
 - serverless.template
 - outputSamTemplate.yaml